---
- name: configure credential in tower
  hosts: all
  #vars:
  #  tower_cred_creation_dir: "./tower-credentials-creation.yml"
  # vars_files:
  #   - ./tower-secrets.yml
  gather_facts: true
  ignore_unreachable: true
  collections:
    - ansible.tower

  tasks:

    - name: return vault secret from path
      ansible.builtin.debug:
        #msg: "{{ lookup('hashi_vault', 'secret=secret/tower_config:github_username auth_method=userpass username=admin password=Pool3ssh! url=http://10.1.196.108:8200') }}"
        msg: "{{ lookup('hashi_vault', 'secret=cubbyhole/secret/tower_config:github_username token=s.3TmyzShE2t209V8GYBgOFYsc url=http://10.1.196.108:8200') }}"
      
    # - name: get token for use during play
    #   uri:
    #     url: "https:10.1.196.125/api/v2/tokens/"
    #     method: POST
    #     user: "admin"
    #     password: "Pool3ssh!"
    #     force_basic_auth: yes
    #     status_code: 201
    #     validate_certs: no
    #   register: user_token
    #   no_log: false

    # - name: make sure bearer token is retrieved from host
    #   debug:
    #     var: user_token


    # - name: set tower oauth token
    #   set_fact:
    #     tower_oauthtoken: "{{ user_token.json.token }}"

    - name: create a token using tower username/password
      awx.awx.tower_token:
        description: 'creating token to test tower jobs'
        scope: 'write'
        state: present
        tower_host: "{{ tower_hostname }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"

    # - name: add credentials
    #   include_role: 
    #     name: redhat_cop.tower_configuration.credentials 
    #   vars:
    #     tower_credentials: "{{ lookup('hashi_vault', 'secret=secret/tower_config:github_username auth_method=userpass username=admin password=Pool3ssh! url=http://10.1.196.108:8200') }}"